version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-planetario
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - planetario-net

  backend:
    build:
      context: ./backend
    container_name: backend-planetario
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - planetario-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend-planetario
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - planetario-net

volumes:
  mysql-data:

networks:
  planetario-net:
    driver: bridge